# Generated by Django 4.2 on 2024-04-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_playlist_profile_song_remove_project_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.profile'),
        ),
    ]
