# Generated by Django 4.2 on 2024-04-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_remove_playlist_songs_song_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songs',
            new_name='playlist',
        ),
    ]
