# Generated by Django 4.2 on 2024-04-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_rename_songs_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.profile', unique=True),
        ),
    ]
